vscode:
  extensions:
    - esbenp.prettier-vscode@3.18.0:SpDMXXww8cAUOXaBCNECgQ==
    - jpoissonnier.vscode-styled-components@0.0.27:6f8dLBHJ6bHiAsfAwvXZNg==
    - Prisma.vscode-graphql@0.2.2:kQK67PfEjC2ZTsRlZVlQAQ==